### ISSUE TITLE
[Prestação de contas] Quebra de página na comprovação financeira

### ISSUE THREAD

**Issue by fernao** [culturagovbr/salic-minc#302]
comprovação financeira
link contrato

CGTEC, nós temos um problema!
Erros processados pela requisição:

 Exceção
Descrição: SQLSTATE[HY000] General SQL Server error: Check messages from the SQL Server (severity 16)
Rastreamento do erro
#0 /var/www/salic/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Pdo/Mssql.php(137): Zend_Db_Adapter_Pdo_Abstract->_connect()
#1 /var/www/salic/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(460): Zend_Db_Adapter_Pdo_Mssql->_connect()
#2 /var/www/salic/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('exec sp_columns...', Array)
#3 /var/www/salic/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Pdo/Mssql.php(237): Zend_Db_Adapter_Pdo_Abstract->query('exec sp_columns...')
#4 /var/www/salic/vendor/zendframework/zendframework1/library/Zend/Db/Table/Abstract.php(836): Zend_Db_Adapter_Pdo_Mssql->describeTable('tbcontratoxagen...', 'dbo')
#5 /var/www/salic/vendor/zendframework/zendframework1/library/Zend/Db/Table/Abstract.php(875): Zend_Db_Table_Abstract->_setupMetadata()
#6 /var/www/salic/vendor/zendframework/zendframework1/library/Zend/Db/Table/Abstract.php(983): Zend_Db_Table_Abstract->_setupPrimaryKey()
#7 /var/www/salic/vendor/zendframework/zendframework1/library/Zend/Db/Table/Select.php(100): Zend_Db_Table_Abstract->info()
#8 /var/www/salic/vendor/zendframework/zendframework1/library/Zend/Db/Table/Select.php(78): Zend_Db_Table_Select->setTable(Object(Contratoxagentes))
#9 /var/www/salic/library/MinC/Db/Table/Select.php(24): Zend_Db_Table_Select->__construct(Object(Contratoxagentes))
#10 /var/www/salic/library/MinC/Db/Table/Abstract.php(286): MinC_Db_Table_Select->__construct(Object(Contratoxagentes))
#11 /var/www/salic/library/MinC/Db/Table/Abstract.php(206): MinC_Db_Table_Abstract->select()
#12 /var/www/salic/application/modules/default/controllers/ComprovarexecucaofinanceiraController.php(657): MinC_Db_Table_Abstract->buscar(Array)
#13 /var/www/salic/application/modules/default/controllers/ComprovarexecucaofinanceiraController.php(573): ComprovarexecucaofinanceiraController->cadastrarVinculoFornecedor(Array)
#14 /var/www/salic/vendor/zendframework/zendframework1/library/Zend/Controller/Action.php(516): ComprovarexecucaofinanceiraController->cadastrarcontratoAction()
#15 /var/www/salic/vendor/zendframework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('cadastrarcontra...')
#16 /var/www/salic/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#17 /var/www/salic/vendor/zendframework/zendframework1/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#18 /var/www/salic/vendor/zendframework/zendframework1/library/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#19 /var/www/salic/index.php(36): Zend_Application->run()
#20 {main}
Parâmetros requisitados
array (
  'controller' => 'comprovarexecucaofinanceira',
  'action' => 'cadastrarcontrato',
  'idusuario' => '426',
  'idpronac' => '202141',
  'module' => 'default',
  'idcontrato' => '',
  'numeroDoContratoSequencial' => '100000',
  'idAgente' => '9343',
  'tpFornecedor' => 'cpf',
  'CNPJCPF' => '239.691.561-49',
  'Descricao' => 'Rômulo Menhô Barbosa',
  'tipoAquisicao' => '1',
  'valorGlobal' => '10.000,00',
  'dataAssinatura' => '26/05/2016',
  'objetoDoContrato' => 'Objeto do Contrato',
  'dataVingenciaInicial' => '27/05/2016',
  'dataVingenciaFinal' => '31/12/2016',
  'produtoSelect' => '0',
  'etapaSelect' => '4',
  'itensSelect' => '',
  'produto' => 
  array (
    0 => '0',
  ),
  'etapa' => 
  array (
    0 => '4',
  ),
)
Proponente está tentando comprovar
Lançamento de contrato

**Comment by fernao** [comment]
Foi feita a correção de quando se vincula um item, mas a falha persiste quando se vinculam todas as etapas ou todos os itens de uma etapa. A regra que permite vincular todas as etapas ou todos itens de uma etapa continua valendo? Vou mover essa dúvida para uma outra issue.
